# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 420ae4ba7841adf8e1a458c139ae46dceba7a894adbfb91973a0865fd4f12f098d75b0ca24d31b3589e417aa6342be6c6102c9abacc58d5ac693fa0733c1321f

test:
  secret_key_base: 2d8be8d0c747824909d658e17e905f669ab221591c16553d3e55e3edb28a3b181067d7a7c09dc643e7fb3dc4e8bf3cf4e09369f4a77f8d01c5ab7dd987a47d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
